# Generated by Django 5.2.9 on 2026-02-18 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='insta_app.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoriteitem',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_favorite', to='insta_app.post'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.ManyToManyField(blank=True, to='insta_app.hashtag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcontent',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_contents', to='insta_app.post'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='insta_app.post'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='data_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
