# Generated by Django 5.2.9 on 2026-02-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0003_alter_comment_created_date_alter_post_created_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=set(),
        ),
    ]
