# Generated by Django 5.2.9 on 2026-02-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0004_alter_commentlike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('users', 'post')},
        ),
    ]
