# Generated by Django 5.2.9 on 2026-02-22 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0005_alter_commentlike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='post_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
